services:
  webserver:
    container_name: PHP-webServer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../www:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql-db
    restart: always
  
  mysql-db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_HOST: '%'
      ports:
        - "3306:3306"
      restart: always
      volumes:
        - mysql-data:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - mysql-db
      ports:
        - "8081:80"
      environment:
        PMA_HOST: mysql-db
        MYSQL_ROOT_PASSWORD: admin

volumes:
  mysql-data: